### ISSUE TITLE
how many models trained if pass in multiple trainingInstanceCount

### ISSUE THREAD

**Issue by jq** [aws/sagemaker-spark#10]
i.e. trainingInstanceCount = 2, then  estimator.fit  returns two models? and each use random partition of training data? or it returns one, if returns one, what should we do to make sure code inside container able to do that?

**Comment by iquintero** [comment]
Hi @jq 
thanks for your interest in SageMaker Spark!. 

**trainingInstanceCount** defines how many EC2 instances are used to train the model with your data. There will be only 1 model returned regardless of how many instances you use for training.  Using more allows more parallelism.

Let me know if this answers  your question or you need a bit more clarification :)

**Comment by jq** [comment]
@iquintero thanks for the answer,  so the model should be designed to work with both single instance and multiple instance? is there a model design framework to follow so that it is compatible with both cases?

**Comment by andremoeller** [comment]
Hi @jq ,

The model itself doesn't have to be designed to work with single or multiple instances, since the model is just a .tar.gz file that a Docker image following this specification can use to make predictions: https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-inference-code.html

However, the algorithm container which trains the model does have to be designed to support distributed training. Documentation on how to make your own algorithm to run on Amazon SageMaker is available here: https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-training-algo.html

Thanks!
