### ISSUE TITLE
Obtaining TrainingJob Name (randomNamePolicy used) from SageMakerModel 

### ISSUE THREAD

**Issue by hdamani09** [aws/sagemaker-spark#100]
Please fill out the form below.

### System Information
- **Spark**:
- **SDK Version**:spark_2.2.0-1.2.5
- **Spark Version**:2.4.3
- **Algorithm**:XGBoost

### Describe the problem
Hi,
I'm trying to obtain the trainingJob name back from a SageMakerModel instance. I'm able to get the _model, endpoint and endpointConfig_ name from the **getCreatedResources** method available for SageMakerModel. But I'm unable to get the trainingJob name incase a **randomNamePolicy** is used to create a dynamic name for the trainingJob. 
Is there a method available for achieving the required?

**Comment by laurenyu** [comment]
Unfortunately, neither `SageMakerEstimator` nor `SageMakerModel` keeps track of the training job that produced the model. You could either use a different name policy or use the API ListTrainingJobs ([docs](https://docs.aws.amazon.com/sagemaker/latest/dg/API_ListTrainingJobs.html)) to find the training job.

**Comment by hdamani09** [comment]
I'm not really sure and haven't tested it yet, but this might return the training job Name **sagemakerModel.namePolicy.trainingJobName**.

**Comment by laurenyu** [comment]
Good eye - that might work? In `fit()`, `SageMakerEstimator` does pass `namePolicy` onto the `SageMakerModel` constructor ([code](https://github.com/aws/sagemaker-spark/blob/master/sagemaker-spark-sdk/src/main/scala/com/amazonaws/services/sagemaker/sparksdk/SageMakerEstimator.scala#L344)) and the random name generation occurs only when `namePolicy` is created ([code](https://github.com/aws/sagemaker-spark/blob/master/sagemaker-spark-sdk/src/main/scala/com/amazonaws/services/sagemaker/sparksdk/NamePolicy.scala#L95-L106)), so that should still be the same training job name from before.

**Comment by hdamani09** [comment]
Yeah, it seems to work fine. Thanks :)
