### ISSUE TITLE
Export SageMakerModel to a XGBoost model

### ISSUE THREAD

**Issue by msobroza** [aws/sagemaker-spark#67]
### System Information
- **Spark or PySpark**: PySpark
- **SDK Version**:
- **Spark Version**:
- **Algorithm (e.g. KMeans)**: XGBoost

### Describe the problem
I would like to know if there is any way to export a trained SageMakerModel to xgboost python model format ?

Thanks you

**Comment by vanetoj** [comment]
are you supposed to import the data too as a csv or is it part of the model. tar file?

**Comment by OlliePage** [comment]
@iquintero this method no longer works. We now get this error message which doesn't provide clear instructions on how to solve. Do you know what we should do in this situation?
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/4608979/76469484-42a5a000-63e6-11ea-9261-dd9224bede63.png">

**Comment by laurenyu** [comment]
@OlliePage thanks for bringing this to our attention. I glanced through the documentation linked in your error message, but didn't see an obvious solution, so I've reached out to the team that manages the SageMaker XGBoost images to see if they have any insight.

**Comment by edwardjkim** [comment]
@OlliePage The error you are seeing is probably due to version mismatch between SageMaker XGBoost and your local installation of XGBoost. The latest SageMaker XGBoost image has XGBoost 0.90, while the latest XGBoost release is 1.0. Since XGBoost 1.0 was released only very recently, the team is still actively working on a new container with XGBoost 1.0. In the meantime, can you check if you are running 1.0 locally? If you would like to load a model that was trained on SageMaker, XGBoost needs to be downgraded to 0.90 with `python -m pip install xgboost==0.90`.

**Comment by vanetoj** [comment]
that was a disaster of errors on part pf the sagemaker - nothing was working. not a fond memory
